---
- hosts: all
  become: true
  tasks:
    - name: Ensure apache is at the latest version
      ansible.builtin.yum:
        name: docker
        state: latest
    - name: Make sure a service unit is running
      ansible.builtin.systemd:
        state: started
        name: docker
